name       : pcsc-lite
version    : 1.9.9
release    : 15
source     :
    - https://github.com/LudovicRousseau/PCSC/archive/refs/tags/1.9.9.tar.gz : 856a1daed9a5ae1ac265c75ce9f81743e66a972e5be5a1d3a2196ed23f75ea26
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
builddeps  :
    - autoconf-archive
setup      : |
    %reconfigure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
