name       : pcsc-lite
version    : 1.8.23
release    : 5
source     :
    - https://alioth.debian.org/frs/download.php/file/4235/pcsc-lite-1.8.23.tar.bz2 : 5a27262586eff39cfd5c19aadc8891dd71c0818d3d629539bd631b958be689c9
license    :
    - BSD-3-Clause
    - GPL-3.0
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
setup      : |
    %configure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
