name       : pcsc-lite
version    : 1.8.21
release    : 3
source     :
    - https://alioth.debian.org/frs/download.php/file/4216/pcsc-lite-1.8.21.tar.bz2 : fe3365eb7d4ce0fe891e2b6d6248351c287435ca502103f1f1431b1710e513ad
license    :
    - BSD-3-Clause
    - GPL-3.0
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
setup      : |
    %configure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
