name       : pcsc-lite
version    : 1.8.24
release    : 6
source     :
    - https://pcsclite.apdu.fr/files/pcsc-lite-1.8.24.tar.bz2 : b81864fa6a5ec776639c02ae89998955f7702a8d10e8b8f70023c5a599d97568
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
setup      : |
    %configure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
