name       : pcsc-lite
version    : 1.9.3
release    : 11
source     :
    - https://github.com/LudovicRousseau/PCSC/archive/refs/tags/1.9.3.tar.gz : 7b7544a2080d53362b2da32800cf3b0ad5d17544af11e339edee4e775b818974
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
builddeps  :
    - autoconf-archive
setup      : |
    %reconfigure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
