name       : pcsc-lite
version    : 1.8.22
release    : 4
source     :
    - https://alioth.debian.org/frs/download.php/file/4225/pcsc-lite-1.8.22.tar.bz2 : 6a358f61ed3b66a7f6e1f4e794a94c7be4c81b7a58ec360c33791e8d7d9bd405
license    :
    - BSD-3-Clause
    - GPL-3.0
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
setup      : |
    %configure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
