name       : pcsc-lite
version    : 1.8.26
release    : 9
source     :
    - https://github.com/LudovicRousseau/PCSC/archive/pcsc-1.8.26.tar.gz : 87da93642ba45fdbec07462c9ffabecbdda02407719fa21402f20fa35910425a
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    Middleware to access a smart card using SCard API (PC/SC)
setup      : |
    %reconfigure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
