name       : pcsc-lite
version    : 1.8.20
release    : 2
source     :
    - https://alioth.debian.org/frs/download.php/file/4203/pcsc-lite-1.8.20.tar.bz2 : ec7d0114016c788c1c09859c84860f6cec6c4595436d23245105154b9c046bb2
license    : BSD-3-Clause
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    PC/SC Architecture smartcard middleware library
setup      : |
    %configure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --enable-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
