name       : pcsc-lite
version    : 1.8.18
release    : 1
source     :
    - http://stroblindustries.com/solus-tarballs/pcsc-lite-1.8.18.tar.bz2 : b22d32b018f6a1016adba91abfcc63876cca999daa472dd86e953ddd41d00905
license    : BSD-3-Clause
component  : programming
summary    : PC/SC Architecture smartcard middleware library
description: |
    PC/SC Architecture smartcard middleware library
setup      : |
    %configure --disable-static \
        --enable-libudev \
        --enable-usbdropdir=%libdir%/pcsc/drivers \
        --enable-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
